import type { CollectionConfig } from 'payload'

import { authenticated } from '@/access/authenticated'

export const ArchiveChunks: CollectionConfig = {
  slug: 'archive-chunks',
  access: {
    create: authenticated,
    delete: authenticated,
    read: authenticated,
    update: authenticated,
  },
  admin: {
    defaultColumns: ['episodeTitle', 'chunkIndex', 'embeddingModel', 'updatedAt'],
    useAsTitle: 'episodeTitle',
  },
  fields: [
    { name: 'episode', type: 'relationship', relationTo: 'episodes', required: true, index: true },
    { name: 'episodeTitle', type: 'text', required: true, index: true },
    { name: 'episodeSlug', type: 'text', required: true, index: true },
    { name: 'sourceType', type: 'select', defaultValue: 'transcript', options: ['transcript'], required: true },
    { name: 'chunkIndex', type: 'number', required: true, index: true },
    { name: 'text', type: 'textarea', required: true },
    { name: 'textHash', type: 'text', required: true, unique: true, index: true },
    { name: 'embeddingModel', type: 'text', required: true, index: true },
    { name: 'embeddingDimension', type: 'number', required: true },
    {
      name: 'embedding',
      type: 'json',
      required: true,
      admin: { description: 'Numeric vector generated by the configured embedding model.' },
    },
  ],
}
